// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

type MetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsService) EXPECT() *MetricsService_Expecter {
	return &MetricsService_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with no fields
func (_m *MetricsService) GetAll() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MetricsService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MetricsService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MetricsService_Expecter) GetAll() *MetricsService_GetAll_Call {
	return &MetricsService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MetricsService_GetAll_Call) Run(run func()) *MetricsService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsService_GetAll_Call) Return(_a0 []string) *MetricsService_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_GetAll_Call) RunAndReturn(run func() []string) *MetricsService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetCounter provides a mock function with given fields: name
func (_m *MetricsService) GetCounter(name string) (int64, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounter'
type MetricsService_GetCounter_Call struct {
	*mock.Call
}

// GetCounter is a helper method to define mock.On call
//   - name string
func (_e *MetricsService_Expecter) GetCounter(name interface{}) *MetricsService_GetCounter_Call {
	return &MetricsService_GetCounter_Call{Call: _e.mock.On("GetCounter", name)}
}

func (_c *MetricsService_GetCounter_Call) Run(run func(name string)) *MetricsService_GetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MetricsService_GetCounter_Call) Return(_a0 int64, _a1 error) *MetricsService_GetCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetCounter_Call) RunAndReturn(run func(string) (int64, error)) *MetricsService_GetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetGauge provides a mock function with given fields: name
func (_m *MetricsService) GetGauge(name string) (float64, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGauge'
type MetricsService_GetGauge_Call struct {
	*mock.Call
}

// GetGauge is a helper method to define mock.On call
//   - name string
func (_e *MetricsService_Expecter) GetGauge(name interface{}) *MetricsService_GetGauge_Call {
	return &MetricsService_GetGauge_Call{Call: _e.mock.On("GetGauge", name)}
}

func (_c *MetricsService_GetGauge_Call) Run(run func(name string)) *MetricsService_GetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MetricsService_GetGauge_Call) Return(_a0 float64, _a1 error) *MetricsService_GetGauge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetGauge_Call) RunAndReturn(run func(string) (float64, error)) *MetricsService_GetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCounter provides a mock function with given fields: name, value
func (_m *MetricsService) RecordCounter(name string, value int64) {
	_m.Called(name, value)
}

// MetricsService_RecordCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCounter'
type MetricsService_RecordCounter_Call struct {
	*mock.Call
}

// RecordCounter is a helper method to define mock.On call
//   - name string
//   - value int64
func (_e *MetricsService_Expecter) RecordCounter(name interface{}, value interface{}) *MetricsService_RecordCounter_Call {
	return &MetricsService_RecordCounter_Call{Call: _e.mock.On("RecordCounter", name, value)}
}

func (_c *MetricsService_RecordCounter_Call) Run(run func(name string, value int64)) *MetricsService_RecordCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MetricsService_RecordCounter_Call) Return() *MetricsService_RecordCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsService_RecordCounter_Call) RunAndReturn(run func(string, int64)) *MetricsService_RecordCounter_Call {
	_c.Run(run)
	return _c
}

// RecordGauge provides a mock function with given fields: name, value
func (_m *MetricsService) RecordGauge(name string, value float64) {
	_m.Called(name, value)
}

// MetricsService_RecordGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordGauge'
type MetricsService_RecordGauge_Call struct {
	*mock.Call
}

// RecordGauge is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *MetricsService_Expecter) RecordGauge(name interface{}, value interface{}) *MetricsService_RecordGauge_Call {
	return &MetricsService_RecordGauge_Call{Call: _e.mock.On("RecordGauge", name, value)}
}

func (_c *MetricsService_RecordGauge_Call) Run(run func(name string, value float64)) *MetricsService_RecordGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MetricsService_RecordGauge_Call) Return() *MetricsService_RecordGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsService_RecordGauge_Call) RunAndReturn(run func(string, float64)) *MetricsService_RecordGauge_Call {
	_c.Run(run)
	return _c
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
