// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/MaxPa1/go-metrics/internal/model"
)

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

type MetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsService) EXPECT() *MetricsService_Expecter {
	return &MetricsService_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *MetricsService) GetAll(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MetricsService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MetricsService_Expecter) GetAll(ctx interface{}) *MetricsService_GetAll_Call {
	return &MetricsService_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MetricsService_GetAll_Call) Run(run func(ctx context.Context)) *MetricsService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MetricsService_GetAll_Call) Return(_a0 []string, _a1 error) *MetricsService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetAll_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MetricsService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetCounter provides a mock function with given fields: ctx, name
func (_m *MetricsService) GetCounter(ctx context.Context, name string) (int64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounter'
type MetricsService_GetCounter_Call struct {
	*mock.Call
}

// GetCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MetricsService_Expecter) GetCounter(ctx interface{}, name interface{}) *MetricsService_GetCounter_Call {
	return &MetricsService_GetCounter_Call{Call: _e.mock.On("GetCounter", ctx, name)}
}

func (_c *MetricsService_GetCounter_Call) Run(run func(ctx context.Context, name string)) *MetricsService_GetCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsService_GetCounter_Call) Return(_a0 int64, _a1 error) *MetricsService_GetCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetCounter_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MetricsService_GetCounter_Call {
	_c.Call.Return(run)
	return _c
}

// GetGauge provides a mock function with given fields: ctx, name
func (_m *MetricsService) GetGauge(ctx context.Context, name string) (float64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGauge'
type MetricsService_GetGauge_Call struct {
	*mock.Call
}

// GetGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MetricsService_Expecter) GetGauge(ctx interface{}, name interface{}) *MetricsService_GetGauge_Call {
	return &MetricsService_GetGauge_Call{Call: _e.mock.On("GetGauge", ctx, name)}
}

func (_c *MetricsService_GetGauge_Call) Run(run func(ctx context.Context, name string)) *MetricsService_GetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsService_GetGauge_Call) Return(_a0 float64, _a1 error) *MetricsService_GetGauge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetGauge_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MetricsService_GetGauge_Call {
	_c.Call.Return(run)
	return _c
}

// RecordBatch provides a mock function with given fields: ctx, metrics
func (_m *MetricsService) RecordBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for RecordBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_RecordBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordBatch'
type MetricsService_RecordBatch_Call struct {
	*mock.Call
}

// RecordBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MetricsService_Expecter) RecordBatch(ctx interface{}, metrics interface{}) *MetricsService_RecordBatch_Call {
	return &MetricsService_RecordBatch_Call{Call: _e.mock.On("RecordBatch", ctx, metrics)}
}

func (_c *MetricsService_RecordBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MetricsService_RecordBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MetricsService_RecordBatch_Call) Return(_a0 error) *MetricsService_RecordBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_RecordBatch_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MetricsService_RecordBatch_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCounter provides a mock function with given fields: ctx, name, value
func (_m *MetricsService) RecordCounter(ctx context.Context, name string, value int64) error {
	ret := _m.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for RecordCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_RecordCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCounter'
type MetricsService_RecordCounter_Call struct {
	*mock.Call
}

// RecordCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value int64
func (_e *MetricsService_Expecter) RecordCounter(ctx interface{}, name interface{}, value interface{}) *MetricsService_RecordCounter_Call {
	return &MetricsService_RecordCounter_Call{Call: _e.mock.On("RecordCounter", ctx, name, value)}
}

func (_c *MetricsService_RecordCounter_Call) Run(run func(ctx context.Context, name string, value int64)) *MetricsService_RecordCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MetricsService_RecordCounter_Call) Return(_a0 error) *MetricsService_RecordCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_RecordCounter_Call) RunAndReturn(run func(context.Context, string, int64) error) *MetricsService_RecordCounter_Call {
	_c.Call.Return(run)
	return _c
}

// RecordGauge provides a mock function with given fields: ctx, name, value
func (_m *MetricsService) RecordGauge(ctx context.Context, name string, value float64) error {
	ret := _m.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for RecordGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_RecordGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordGauge'
type MetricsService_RecordGauge_Call struct {
	*mock.Call
}

// RecordGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value float64
func (_e *MetricsService_Expecter) RecordGauge(ctx interface{}, name interface{}, value interface{}) *MetricsService_RecordGauge_Call {
	return &MetricsService_RecordGauge_Call{Call: _e.mock.On("RecordGauge", ctx, name, value)}
}

func (_c *MetricsService_RecordGauge_Call) Run(run func(ctx context.Context, name string, value float64)) *MetricsService_RecordGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MetricsService_RecordGauge_Call) Return(_a0 error) *MetricsService_RecordGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_RecordGauge_Call) RunAndReturn(run func(context.Context, string, float64) error) *MetricsService_RecordGauge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
