// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxPa1/go-metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MetricsStorage is an autogenerated mock type for the MetricsStorage type
type MetricsStorage struct {
	mock.Mock
}

type MetricsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsStorage) EXPECT() *MetricsStorage_Expecter {
	return &MetricsStorage_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx
func (_m *MetricsStorage) FindAll(ctx context.Context) (map[string]int64, map[string]float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 map[string]int64
	var r1 map[string]float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int64, map[string]float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) map[string]float64); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetricsStorage_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MetricsStorage_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MetricsStorage_Expecter) FindAll(ctx interface{}) *MetricsStorage_FindAll_Call {
	return &MetricsStorage_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MetricsStorage_FindAll_Call) Run(run func(ctx context.Context)) *MetricsStorage_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MetricsStorage_FindAll_Call) Return(_a0 map[string]int64, _a1 map[string]float64, _a2 error) *MetricsStorage_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MetricsStorage_FindAll_Call) RunAndReturn(run func(context.Context) (map[string]int64, map[string]float64, error)) *MetricsStorage_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindCounter provides a mock function with given fields: ctx, name
func (_m *MetricsStorage) FindCounter(ctx context.Context, name string) (int64, bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindCounter")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetricsStorage_FindCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCounter'
type MetricsStorage_FindCounter_Call struct {
	*mock.Call
}

// FindCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MetricsStorage_Expecter) FindCounter(ctx interface{}, name interface{}) *MetricsStorage_FindCounter_Call {
	return &MetricsStorage_FindCounter_Call{Call: _e.mock.On("FindCounter", ctx, name)}
}

func (_c *MetricsStorage_FindCounter_Call) Run(run func(ctx context.Context, name string)) *MetricsStorage_FindCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsStorage_FindCounter_Call) Return(_a0 int64, _a1 bool, _a2 error) *MetricsStorage_FindCounter_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MetricsStorage_FindCounter_Call) RunAndReturn(run func(context.Context, string) (int64, bool, error)) *MetricsStorage_FindCounter_Call {
	_c.Call.Return(run)
	return _c
}

// FindGauge provides a mock function with given fields: ctx, name
func (_m *MetricsStorage) FindGauge(ctx context.Context, name string) (float64, bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindGauge")
	}

	var r0 float64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetricsStorage_FindGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGauge'
type MetricsStorage_FindGauge_Call struct {
	*mock.Call
}

// FindGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MetricsStorage_Expecter) FindGauge(ctx interface{}, name interface{}) *MetricsStorage_FindGauge_Call {
	return &MetricsStorage_FindGauge_Call{Call: _e.mock.On("FindGauge", ctx, name)}
}

func (_c *MetricsStorage_FindGauge_Call) Run(run func(ctx context.Context, name string)) *MetricsStorage_FindGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MetricsStorage_FindGauge_Call) Return(_a0 float64, _a1 bool, _a2 error) *MetricsStorage_FindGauge_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MetricsStorage_FindGauge_Call) RunAndReturn(run func(context.Context, string) (float64, bool, error)) *MetricsStorage_FindGauge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function with given fields: ctx, metrics
func (_m *MetricsStorage) UpdateBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsStorage_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MetricsStorage_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MetricsStorage_Expecter) UpdateBatch(ctx interface{}, metrics interface{}) *MetricsStorage_UpdateBatch_Call {
	return &MetricsStorage_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, metrics)}
}

func (_c *MetricsStorage_UpdateBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MetricsStorage_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MetricsStorage_UpdateBatch_Call) Return(_a0 error) *MetricsStorage_UpdateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsStorage_UpdateBatch_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MetricsStorage_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function with given fields: ctx, name, value
func (_m *MetricsStorage) UpdateCounter(ctx context.Context, name string, value int64) error {
	ret := _m.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsStorage_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MetricsStorage_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value int64
func (_e *MetricsStorage_Expecter) UpdateCounter(ctx interface{}, name interface{}, value interface{}) *MetricsStorage_UpdateCounter_Call {
	return &MetricsStorage_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", ctx, name, value)}
}

func (_c *MetricsStorage_UpdateCounter_Call) Run(run func(ctx context.Context, name string, value int64)) *MetricsStorage_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MetricsStorage_UpdateCounter_Call) Return(_a0 error) *MetricsStorage_UpdateCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsStorage_UpdateCounter_Call) RunAndReturn(run func(context.Context, string, int64) error) *MetricsStorage_UpdateCounter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGauge provides a mock function with given fields: ctx, name, value
func (_m *MetricsStorage) UpdateGauge(ctx context.Context, name string, value float64) error {
	ret := _m.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsStorage_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MetricsStorage_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value float64
func (_e *MetricsStorage_Expecter) UpdateGauge(ctx interface{}, name interface{}, value interface{}) *MetricsStorage_UpdateGauge_Call {
	return &MetricsStorage_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", ctx, name, value)}
}

func (_c *MetricsStorage_UpdateGauge_Call) Run(run func(ctx context.Context, name string, value float64)) *MetricsStorage_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MetricsStorage_UpdateGauge_Call) Return(_a0 error) *MetricsStorage_UpdateGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsStorage_UpdateGauge_Call) RunAndReturn(run func(context.Context, string, float64) error) *MetricsStorage_UpdateGauge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetricsStorage creates a new instance of MetricsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsStorage {
	mock := &MetricsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
