// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsStorage is an autogenerated mock type for the MetricsStorage type
type MetricsStorage struct {
	mock.Mock
}

type MetricsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsStorage) EXPECT() *MetricsStorage_Expecter {
	return &MetricsStorage_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with no fields
func (_m *MetricsStorage) FindAll() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MetricsStorage_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MetricsStorage_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MetricsStorage_Expecter) FindAll() *MetricsStorage_FindAll_Call {
	return &MetricsStorage_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MetricsStorage_FindAll_Call) Run(run func()) *MetricsStorage_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricsStorage_FindAll_Call) Return(_a0 []string) *MetricsStorage_FindAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsStorage_FindAll_Call) RunAndReturn(run func() []string) *MetricsStorage_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindCounter provides a mock function with given fields: name
func (_m *MetricsStorage) FindCounter(name string) (int64, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindCounter")
	}

	var r0 int64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (int64, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MetricsStorage_FindCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCounter'
type MetricsStorage_FindCounter_Call struct {
	*mock.Call
}

// FindCounter is a helper method to define mock.On call
//   - name string
func (_e *MetricsStorage_Expecter) FindCounter(name interface{}) *MetricsStorage_FindCounter_Call {
	return &MetricsStorage_FindCounter_Call{Call: _e.mock.On("FindCounter", name)}
}

func (_c *MetricsStorage_FindCounter_Call) Run(run func(name string)) *MetricsStorage_FindCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MetricsStorage_FindCounter_Call) Return(_a0 int64, _a1 bool) *MetricsStorage_FindCounter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsStorage_FindCounter_Call) RunAndReturn(run func(string) (int64, bool)) *MetricsStorage_FindCounter_Call {
	_c.Call.Return(run)
	return _c
}

// FindGauge provides a mock function with given fields: name
func (_m *MetricsStorage) FindGauge(name string) (float64, bool) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindGauge")
	}

	var r0 float64
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (float64, bool)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MetricsStorage_FindGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGauge'
type MetricsStorage_FindGauge_Call struct {
	*mock.Call
}

// FindGauge is a helper method to define mock.On call
//   - name string
func (_e *MetricsStorage_Expecter) FindGauge(name interface{}) *MetricsStorage_FindGauge_Call {
	return &MetricsStorage_FindGauge_Call{Call: _e.mock.On("FindGauge", name)}
}

func (_c *MetricsStorage_FindGauge_Call) Run(run func(name string)) *MetricsStorage_FindGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MetricsStorage_FindGauge_Call) Return(_a0 float64, _a1 bool) *MetricsStorage_FindGauge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsStorage_FindGauge_Call) RunAndReturn(run func(string) (float64, bool)) *MetricsStorage_FindGauge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function with given fields: name, value
func (_m *MetricsStorage) UpdateCounter(name string, value int64) {
	_m.Called(name, value)
}

// MetricsStorage_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MetricsStorage_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - name string
//   - value int64
func (_e *MetricsStorage_Expecter) UpdateCounter(name interface{}, value interface{}) *MetricsStorage_UpdateCounter_Call {
	return &MetricsStorage_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", name, value)}
}

func (_c *MetricsStorage_UpdateCounter_Call) Run(run func(name string, value int64)) *MetricsStorage_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *MetricsStorage_UpdateCounter_Call) Return() *MetricsStorage_UpdateCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsStorage_UpdateCounter_Call) RunAndReturn(run func(string, int64)) *MetricsStorage_UpdateCounter_Call {
	_c.Run(run)
	return _c
}

// UpdateGauge provides a mock function with given fields: name, value
func (_m *MetricsStorage) UpdateGauge(name string, value float64) {
	_m.Called(name, value)
}

// MetricsStorage_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MetricsStorage_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *MetricsStorage_Expecter) UpdateGauge(name interface{}, value interface{}) *MetricsStorage_UpdateGauge_Call {
	return &MetricsStorage_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", name, value)}
}

func (_c *MetricsStorage_UpdateGauge_Call) Run(run func(name string, value float64)) *MetricsStorage_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MetricsStorage_UpdateGauge_Call) Return() *MetricsStorage_UpdateGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsStorage_UpdateGauge_Call) RunAndReturn(run func(string, float64)) *MetricsStorage_UpdateGauge_Call {
	_c.Run(run)
	return _c
}

// NewMetricsStorage creates a new instance of MetricsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsStorage {
	mock := &MetricsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
